[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
polling_app = "AEaXC6N4s4eFDoASXjaWH7r9RRKv6XGdqbHQLnNUx9m9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
